import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  safelist: [
    "text-primary", "text-secondary", "text-heart", "text-dna", "text-amber", "text-muted-foreground",
    "bg-primary/15", "bg-secondary/15", "bg-heart/15", "bg-dna/15", "bg-amber/15",
    "border-primary/30", "border-secondary/30", "border-heart/30", "border-dna/30", "border-amber/30",
    "from-primary/15", "from-secondary/15", "from-heart/15", "from-dna/15", "from-amber/15",
    "from-primary/12", "from-secondary/12", "from-heart/12", "from-dna/12", "from-amber/12",
    "to-cyan-bright/8", "to-purple-light/8", "to-heart/8", "to-dna/8", "to-amber/8",
    "to-cyan-bright/10", "to-purple-light/10", "to-heart/10", "to-dna/10",
    "from-primary", "to-cyan-bright", "from-secondary", "to-purple-light", "from-heart", "to-heart/60", "from-dna", "to-dna/60", "from-amber", "to-amber/60",
  ],
  theme: {
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Orbitron', 'Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        success: { DEFAULT: "hsl(var(--success))", foreground: "hsl(var(--success-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        cyan: "hsl(var(--cyan))",
        "cyan-bright": "hsl(var(--cyan-bright))",
        purple: "hsl(var(--purple))",
        "purple-light": "hsl(var(--purple-light))",
        heart: "hsl(var(--heart))",
        dna: "hsl(var(--dna))",
        amber: "hsl(var(--amber))",
        navy: "hsl(var(--navy))",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in": { "0%": { opacity: "0", transform: "translateY(20px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "fade-in-slow": { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        "float": { "0%,100%": { transform: "translateY(0px) translateX(0px)" }, "33%": { transform: "translateY(-20px) translateX(10px)" }, "66%": { transform: "translateY(10px) translateX(-15px)" } },
        "pulse-glow": { "0%,100%": { opacity: "0.4", transform: "scale(1)" }, "50%": { opacity: "0.7", transform: "scale(1.08)" } },
        "gradient-shift": { "0%,100%": { backgroundPosition: "0% 50%" }, "50%": { backgroundPosition: "100% 50%" } },
        "scale-in": { "0%": { opacity: "0", transform: "scale(0.9)" }, "100%": { opacity: "1", transform: "scale(1)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.8s cubic-bezier(0.4,0,0.2,1) forwards",
        "fade-in-slow": "fade-in-slow 1.5s ease-out forwards",
        "float": "float 8s ease-in-out infinite",
        "float-slow": "float 12s ease-in-out infinite",
        "pulse-glow": "pulse-glow 4s ease-in-out infinite",
        "gradient-shift": "gradient-shift 8s ease infinite",
        "scale-in": "scale-in 0.5s cubic-bezier(0.4,0,0.2,1) forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
